name: dti_reviewer
channels:
  - conda-forge
dependencies:
  - flask
  - flask-login
  - authlib
  - flask-wtf
  - pandas
  - scipy
  - scikit-learn
  - flask_cors
  - gunicorn
  - pytest
  - sphinx
  - celery
  - redis-py
  - pytables

